name: Teste Build

on: 
  workflow_dispatch: #Disparo manual

jobs:
  build-image-docker:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Config Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        run: docker build -t ${{ secrets.CONTAINER_IMAGE }}:teste .
